interface PlantSpriteProps {
  state?: 'happy' | 'neutral' | 'sad' | 'sick' | 'evolving';
  size?: 'sm' | 'md' | 'lg';
  xp?: number;
}

export function PlantSprite({ state = 'happy', size = 'md', xp = 0 }: PlantSpriteProps) {
  const sizeClasses = {
    sm: 'w-16 h-16',
    md: 'w-24 h-24',
    lg: 'w-32 h-32'
  };

  const stateEmojis = {
    happy: '🌱',
    neutral: '🌿',
    sad: '🍂',
    sick: '🥀',
    evolving: '✨'
  };

  return (
    <div className="flex flex-col items-center gap-2">
      <div className={`${sizeClasses[size]} pixel-border bg-[var(--wheat)] flex items-center justify-center pixel-shadow relative overflow-hidden`}>
        {/* Pixel sprite placeholder - will be generated by Gemini 2.5 Flash */}
        <span className="text-[48px]">{stateEmojis[state]}</span>
        
        {state === 'evolving' && (
          <div className="absolute inset-0 bg-[var(--sprout)] opacity-20 animate-pulse"></div>
        )}
      </div>
      
      {/* XP Bar */}
      {xp !== undefined && (
        <div className="w-full max-w-[120px]">
          <div className="h-2 pixel-border bg-[var(--sand)] overflow-hidden">
            <div 
              className="h-full bg-[var(--sprout)] transition-all duration-300"
              style={{ width: `${Math.min(xp, 100)}%` }}
            />
          </div>
          <p className="text-[8px] text-[var(--khaki)] text-center mt-1">XP: {xp}%</p>
        </div>
      )}
    </div>
  );
}
